#!/usr/bin/env python3
"""Generate the FACTOR ASERT log2(compute) lookup table.

Formula: log2_compute(n) = 0.0301 * log2(R) * n + 2 * log2(n)
where R = 3.8 and n is an even integer in [2, 1022].

Output: C++ header with 511-entry Q32.32 fixed-point int64_t array.
Usage: python3 scripts/gen_compute_table.py > src/asert_table.h
"""

import decimal
import hashlib
import sys

# Parameters
R = decimal.Decimal("3.8")
COEFF = decimal.Decimal("0.0301")
NBITS_MIN = 2
NBITS_MAX = 1022
Q32 = 2**32


def log2_decimal(x: decimal.Decimal) -> decimal.Decimal:
    """Compute log2(x) in high-precision Decimal arithmetic."""
    return x.ln() / decimal.Decimal(2).ln()


def main():
    decimal.getcontext().prec = 60

    log2_R = log2_decimal(R)

    entries: list[tuple[int, int]] = []
    prev = None
    for i in range(511):
        n = 2 * (i + 1)  # even integers 2, 4, 6, ..., 1022
        log2_n = log2_decimal(decimal.Decimal(n))
        value = COEFF * log2_R * n + 2 * log2_n
        q32_value = int(
            (value * Q32).to_integral_value(rounding=decimal.ROUND_HALF_EVEN)
        )

        if prev is not None:
            assert q32_value > prev, (
                f"Table not monotonically increasing at nBits={n}: "
                f"{q32_value} <= {prev}"
            )
        prev = q32_value
        entries.append((n, q32_value))

    lines: list[str] = []
    lines.append("// Copyright (c) 2026 The FACTOR developers")
    lines.append("// Distributed under the MIT software license, see the accompanying")
    lines.append(
        "// file COPYING or http://www.opensource.org/licenses/mit-license.php."
    )
    lines.append("")
    lines.append("#ifndef BITCOIN_ASERT_TABLE_H")
    lines.append("#define BITCOIN_ASERT_TABLE_H")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append(
        "// log2(compute(nBits)) in Q32.32 fixed-point for every valid even nBits."
    )
    lines.append("// Index i corresponds to nBits = 2*(i+1).")
    lines.append("// Formula: log2_compute(n) = 0.0301 * log2(3.8) * n + 2 * log2(n)")
    lines.append("// Generated by scripts/gen_compute_table.py")
    lines.append("static const int64_t LOG2_COMPUTE_TABLE[511] = {")
    for n, val in entries:
        lines.append(f"    {val:>20}LL, /* nBits={n:4d} */")
    lines.append("};")
    lines.append("")
    lines.append("#endif // BITCOIN_ASERT_TABLE_H")
    lines.append("")

    output = "\n".join(lines)
    _ = sys.stdout.write(output)

    sha = hashlib.sha256(output.encode("utf-8")).hexdigest()
    print(f"SHA-256: {sha}", file=sys.stderr)


if __name__ == "__main__":
    main()
